[project]
name = "focpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "markdownify>=1.1.0",
    "meilisearch>=0.34.1",
]
